/*
Instituto Tecnológico Superior de Tacámbaro
Ingeniería en Sistemas Computacionales 
5º Semestre
Docente: MC Oscar Alvarez Arriaga   
Almunos: Celestino Moreno Rodrigez N.Control: 20940087
          Luis Alberto Zavala cruz N.Control: 
          Jair Ziranda Villalon N.Control:

Este es un programa el cual genera numeros pseudoaleatorios a partir del método congruencial mixto
y que estos posteriormente son validos las pruebas estadicas de medias, varianza y forma.
*/
package Clases;

import java.awt.Color;
import java.awt.Image;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Celes
 */
public class Pruebas extends javax.swing.JFrame {

    double media = 0;
    double zTab = 0;
    double chiCuadradaPoker=0;
    double confiabilidad = 0;
   
    double arrayEjemplo [] = {0.37206,0.40601,0.84726,0.57572,0.04961,0.21932,0.42298,0.06658,0.43995,0.28721,0.30418,0.52480,0.38903,0.62663,0.71149,0.81332,0.13446,0.32115,0.74543,0.25326};
    double X2tabSeriesTabla=0;
    int contadorAceptacion = 0;
    
    public Pruebas() {
        initComponents();
        setSize(1842, 800);
        media();
        
        botones.add(rd99);
        botones.add(rd95);
        botones.add(rd90);
        
        
       lblAceptacion.setVisible(false);
       lblResultado.setVisible(false);
       lblValoresVarianza.setVisible(false);
       lblAceptacionVarianza.setVisible(false);
       lblresultadoForma.setVisible(false);
       lblAceptacionPoker.setVisible(false);
       lblresultadoForma.setVisible(false);
       lblAceptacionForma.setVisible(false);
       lblResultadoPoker.setVisible(false);
       lblValoresAceptacionCorridas.setVisible(false);
       lblAceptacionCorridas.setVisible(false);
       lblValoresSeries.setVisible(false);
       lblAceptacionSeries.setVisible(false);
       lblAceptacionNumeros.setVisible(false);
       btnSmulacion.setVisible(false);
       imagenAceptacionMedias.setVisible(false);
       imagenAceptacionForma.setVisible(false);
       imagenAceptacionPoker.setVisible(false);
       imagenAceptacionCorridas.setVisible(false);
       imageAceptacionSeries.setVisible(false);
       this.setLocationRelativeTo(null);
        panel.setBackground(new Color(98,19,50));
        panelAbajo.setBackground(new Color(195,182,159));
        
        btnNuevosNumeros.setBackground(Color.WHITE);
        btnRealizar.setBackground(Color.WHITE);
        btnSmulacion.setBackground(Color.WHITE);
     

    }
    public void media(){
        Interfaz u = new Interfaz();
        double auxiliar = 0;
        for (int i = 0; i < u.arrayAleatorios.length; i++) {
            auxiliar += u.arrayAleatorios[i];
            media = auxiliar/u.arrayAleatorios.length;
        }
        media = Math.round(media*100000) / 100000d;
       
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botones = new javax.swing.ButtonGroup();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblMedias = new javax.swing.JLabel();
        lblLimiteInferior = new javax.swing.JLabel();
        lblLimiteSuperior = new javax.swing.JLabel();
        lblZtab = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnRealizar = new javax.swing.JButton();
        rd99 = new javax.swing.JRadioButton();
        rd95 = new javax.swing.JRadioButton();
        rd90 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lblAceptacion = new javax.swing.JLabel();
        lblVarianza = new javax.swing.JLabel();
        lblVarianzaInferior = new javax.swing.JLabel();
        lblVarianzaSuperior = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAceptacionVarianza = new javax.swing.JLabel();
        lblValoresVarianza = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        lblFOclase10 = new javax.swing.JLabel();
        lblFOclase1 = new javax.swing.JLabel();
        lblFOclase2 = new javax.swing.JLabel();
        lblFOclase3 = new javax.swing.JLabel();
        lblFOclase4 = new javax.swing.JLabel();
        lblFOclase5 = new javax.swing.JLabel();
        lblFOclase6 = new javax.swing.JLabel();
        lblFOclase7 = new javax.swing.JLabel();
        lblFOclase8 = new javax.swing.JLabel();
        lblFOclase9 = new javax.swing.JLabel();
        lblX2TabPoker = new javax.swing.JLabel();
        lblX2calculadaPoker = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblAceptacionPoker = new javax.swing.JLabel();
        lblresultadoForma = new javax.swing.JLabel();
        FE1 = new javax.swing.JLabel();
        FE2 = new javax.swing.JLabel();
        FE3 = new javax.swing.JLabel();
        FE4 = new javax.swing.JLabel();
        FE5 = new javax.swing.JLabel();
        FE6 = new javax.swing.JLabel();
        FE7 = new javax.swing.JLabel();
        FE8 = new javax.swing.JLabel();
        FE9 = new javax.swing.JLabel();
        FE10 = new javax.swing.JLabel();
        btnNuevosNumeros = new javax.swing.JButton();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        FOquintilla = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        FEquintilla = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jLabel43 = new javax.swing.JLabel();
        FEpachuca = new javax.swing.JLabel();
        FEunPar = new javax.swing.JLabel();
        FEdosPares = new javax.swing.JLabel();
        FEtercia = new javax.swing.JLabel();
        FEfull = new javax.swing.JLabel();
        FEpoker = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        FOpachuca = new javax.swing.JLabel();
        FOunPar = new javax.swing.JLabel();
        FOdosPares = new javax.swing.JLabel();
        FOtercia = new javax.swing.JLabel();
        FOfull = new javax.swing.JLabel();
        FOpoker = new javax.swing.JLabel();
        lblX2calculadaForma = new javax.swing.JLabel();
        lblX2TabForma = new javax.swing.JLabel();
        lblResultadoPoker = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblAceptacionForma = new javax.swing.JLabel();
        jSeparator37 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JSeparator();
        lblValorHcorridas = new javax.swing.JLabel();
        lblValorEcorridas = new javax.swing.JLabel();
        lblValorVcorridas = new javax.swing.JLabel();
        lblZcalculadaCorridas = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblZtabCorridas = new javax.swing.JLabel();
        lblAceptacionCorridas = new javax.swing.JLabel();
        lblValoresAceptacionCorridas = new javax.swing.JLabel();
        jSeparator39 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        jSeparator47 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jSeparator50 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lblCasilla1 = new javax.swing.JLabel();
        lblCasilla2 = new javax.swing.JLabel();
        lblCasilla3 = new javax.swing.JLabel();
        lblCasilla4 = new javax.swing.JLabel();
        lblCasilla5 = new javax.swing.JLabel();
        lblCasilla6 = new javax.swing.JLabel();
        lblCasilla7 = new javax.swing.JLabel();
        lblCasilla8 = new javax.swing.JLabel();
        lblCasilla9 = new javax.swing.JLabel();
        lblCasilla10 = new javax.swing.JLabel();
        lblCasilla11 = new javax.swing.JLabel();
        lblCasilla12 = new javax.swing.JLabel();
        lblCasilla13 = new javax.swing.JLabel();
        lblCasilla14 = new javax.swing.JLabel();
        lblCasilla15 = new javax.swing.JLabel();
        lblCasilla16 = new javax.swing.JLabel();
        lblParejasSeries = new javax.swing.JLabel();
        lblFEseries = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        lblValoresSeries = new javax.swing.JLabel();
        lblAceptacionSeries = new javax.swing.JLabel();
        lblX2calculadaSeries = new javax.swing.JLabel();
        lblx2TabSeries = new javax.swing.JLabel();
        lblAceptacionNumeros = new javax.swing.JLabel();
        btnSmulacion = new javax.swing.JButton();
        imagenAceptacionMedias = new javax.swing.JLabel();
        imagenAceptacionVarianza = new javax.swing.JLabel();
        imagenAceptacionForma = new javax.swing.JLabel();
        imagenAceptacionPoker = new javax.swing.JLabel();
        imagenAceptacionCorridas = new javax.swing.JLabel();
        imageAceptacionSeries = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        panelAbajo = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("nivel de confianza");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 170, 19);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 74, 1860, 10);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(600, 110, 10, 240);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(250, 70, 10, 710);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Prueba de medias");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 160, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Varianza");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 80, 59, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Series");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1550, 70, 80, 30);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 100, 1850, 10);

        lblMedias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMedias.setText("Media");
        getContentPane().add(lblMedias);
        lblMedias.setBounds(20, 130, 200, 19);

        lblLimiteInferior.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLimiteInferior.setText("Limite inferior:");
        getContentPane().add(lblLimiteInferior);
        lblLimiteInferior.setBounds(20, 180, 210, 19);

        lblLimiteSuperior.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLimiteSuperior.setText("Limite superior:");
        getContentPane().add(lblLimiteSuperior);
        lblLimiteSuperior.setBounds(20, 230, 210, 19);

        lblZtab.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblZtab.setText("Ztab:");
        getContentPane().add(lblZtab);
        lblZtab.setBounds(20, 290, 190, 19);

        lblResultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(80, 630, 130, 30);

        btnRealizar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRealizar.setText("Realizar pruebas");
        btnRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizar);
        btnRealizar.setBounds(260, 30, 160, 30);

        rd99.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rd99.setForeground(new java.awt.Color(255, 255, 255));
        rd99.setText("99%");
        rd99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd99ActionPerformed(evt);
            }
        });
        getContentPane().add(rd99);
        rd99.setBounds(20, 30, 60, 28);

        rd95.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rd95.setForeground(new java.awt.Color(255, 255, 255));
        rd95.setText("95%");
        getContentPane().add(rd95);
        rd95.setBounds(100, 30, 60, 28);

        rd90.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rd90.setForeground(new java.awt.Color(255, 255, 255));
        rd90.setText("90%");
        getContentPane().add(rd90);
        rd90.setBounds(170, 30, 70, 28);

        jLabel5.setText("Limite inferior ≤ media ≤ Limite superior");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 340, 250, 16);

        lblAceptacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAceptacion.setText("jLabel6");
        getContentPane().add(lblAceptacion);
        lblAceptacion.setBounds(0, 370, 250, 20);

        lblVarianza.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVarianza.setText("Varianza: ");
        getContentPane().add(lblVarianza);
        lblVarianza.setBounds(270, 130, 210, 19);

        lblVarianzaInferior.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVarianzaInferior.setText("limite inferior:");
        getContentPane().add(lblVarianzaInferior);
        lblVarianzaInferior.setBounds(270, 170, 230, 19);

        lblVarianzaSuperior.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVarianzaSuperior.setText("limite superior:");
        getContentPane().add(lblVarianzaSuperior);
        lblVarianzaSuperior.setBounds(270, 210, 230, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Lim inf ≤ varianza ≤ Superior");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 330, 220, 19);

        lblAceptacionVarianza.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAceptacionVarianza.setText(".");
        getContentPane().add(lblAceptacionVarianza);
        lblAceptacionVarianza.setBounds(340, 650, 150, 16);

        lblValoresVarianza.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValoresVarianza.setText(".");
        getContentPane().add(lblValoresVarianza);
        lblValoresVarianza.setBounds(260, 360, 230, 16);

        jLabel7.setText("0.9-1.0");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(610, 330, 38, 20);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(530, 170, 220, 2);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(810, 110, 20, 270);

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(530, 110, 220, 10);

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(530, 110, 10, 240);

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(660, 110, 10, 240);

        jLabel8.setText("FE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(720, 120, 30, 20);

        jLabel9.setText("No. Clase");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(540, 120, 53, 16);

        jLabel10.setText("2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(560, 160, 7, 40);

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator11);
        jSeparator11.setBounds(710, 110, 10, 240);

        jLabel11.setText("Intervalo");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(610, 120, 60, 16);

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(750, 110, 10, 240);

        jLabel12.setText("FO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(670, 120, 60, 20);

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator13);
        jSeparator13.setBounds(810, 110, 220, 10);

        jLabel13.setText("1");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(560, 150, 7, 16);

        jLabel14.setText("0.0 - 0.1");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(610, 150, 44, 16);

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator14);
        jSeparator14.setBounds(530, 350, 220, 10);

        jLabel15.setText("10");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(560, 330, 20, 20);

        jLabel16.setText("0.1 - 0.2");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(610, 170, 44, 20);

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator15);
        jSeparator15.setBounds(530, 190, 220, 10);

        jLabel17.setText("3");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(560, 180, 20, 40);

        jLabel18.setText("5");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(560, 220, 20, 40);

        jLabel19.setText("0.2 - 0.3");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(610, 190, 44, 20);

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator16);
        jSeparator16.setBounds(530, 210, 220, 10);

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator17);
        jSeparator17.setBounds(530, 230, 220, 10);

        jLabel20.setText("4");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(560, 200, 20, 40);

        jLabel21.setText("0.3 - 0.4");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(610, 210, 44, 20);

        jLabel22.setText("0.4 - 0.5");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(610, 230, 44, 20);

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator18);
        jSeparator18.setBounds(530, 250, 220, 10);

        jLabel23.setText("6");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(560, 250, 20, 20);

        jLabel24.setText("0.5 - 0.6");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(610, 250, 44, 20);

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator19);
        jSeparator19.setBounds(530, 270, 220, 10);

        jLabel25.setText("7");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(560, 270, 20, 20);

        jLabel26.setText("0.6 - 0.7");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(610, 270, 44, 20);

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator20);
        jSeparator20.setBounds(530, 290, 220, 10);

        jLabel27.setText("8");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(560, 290, 20, 20);

        jLabel28.setText("0.7 - 0.8");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(610, 290, 44, 20);

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator21);
        jSeparator21.setBounds(530, 310, 220, 10);

        jLabel29.setText("9");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(560, 310, 20, 20);

        jLabel30.setText("0.8 - 0.9");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(610, 310, 44, 20);

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator22);
        jSeparator22.setBounds(530, 330, 220, 10);

        lblFOclase10.setText("FO");
        getContentPane().add(lblFOclase10);
        lblFOclase10.setBounds(670, 330, 30, 16);

        lblFOclase1.setText("FO");
        getContentPane().add(lblFOclase1);
        lblFOclase1.setBounds(670, 150, 30, 16);

        lblFOclase2.setText("FO");
        getContentPane().add(lblFOclase2);
        lblFOclase2.setBounds(670, 170, 30, 16);

        lblFOclase3.setText("FO");
        getContentPane().add(lblFOclase3);
        lblFOclase3.setBounds(670, 190, 30, 16);

        lblFOclase4.setText("FO");
        getContentPane().add(lblFOclase4);
        lblFOclase4.setBounds(670, 210, 30, 16);

        lblFOclase5.setText("FO");
        getContentPane().add(lblFOclase5);
        lblFOclase5.setBounds(670, 230, 30, 16);

        lblFOclase6.setText("FO");
        getContentPane().add(lblFOclase6);
        lblFOclase6.setBounds(670, 250, 30, 16);

        lblFOclase7.setText("FO");
        getContentPane().add(lblFOclase7);
        lblFOclase7.setBounds(670, 270, 30, 16);

        lblFOclase8.setText("FO");
        getContentPane().add(lblFOclase8);
        lblFOclase8.setBounds(670, 290, 30, 16);

        lblFOclase9.setText("FO");
        getContentPane().add(lblFOclase9);
        lblFOclase9.setBounds(670, 310, 30, 16);

        lblX2TabPoker.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblX2TabPoker.setText("x² Tab: ");
        getContentPane().add(lblX2TabPoker);
        lblX2TabPoker.setBounds(820, 430, 170, 19);

        lblX2calculadaPoker.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblX2calculadaPoker.setText("x² calculada: ");
        getContentPane().add(lblX2calculadaPoker);
        lblX2calculadaPoker.setBounds(820, 400, 210, 19);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setText("x² calc ≤ x²tab ");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(870, 450, 110, 19);

        lblAceptacionPoker.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAceptacionPoker.setText("jLabel323");
        getContentPane().add(lblAceptacionPoker);
        lblAceptacionPoker.setBounds(880, 710, 120, 19);

        lblresultadoForma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblresultadoForma.setText("jLabel32");
        getContentPane().add(lblresultadoForma);
        lblresultadoForma.setBounds(570, 420, 190, 19);

        FE1.setText("FE");
        getContentPane().add(FE1);
        FE1.setBounds(720, 330, 48, 20);

        FE2.setText("FE");
        getContentPane().add(FE2);
        FE2.setBounds(720, 150, 48, 16);

        FE3.setText("FE");
        getContentPane().add(FE3);
        FE3.setBounds(720, 170, 48, 16);

        FE4.setText("FE");
        getContentPane().add(FE4);
        FE4.setBounds(720, 190, 48, 16);

        FE5.setText("FE");
        getContentPane().add(FE5);
        FE5.setBounds(720, 210, 48, 20);

        FE6.setText("FE");
        getContentPane().add(FE6);
        FE6.setBounds(720, 230, 48, 16);

        FE7.setText("FE");
        getContentPane().add(FE7);
        FE7.setBounds(720, 250, 48, 16);

        FE8.setText("FE");
        getContentPane().add(FE8);
        FE8.setBounds(720, 270, 48, 16);

        FE9.setText("FE");
        getContentPane().add(FE9);
        FE9.setBounds(720, 290, 48, 20);

        FE10.setText("FE");
        getContentPane().add(FE10);
        FE10.setBounds(720, 310, 48, 20);

        btnNuevosNumeros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNuevosNumeros.setText("Generar nuevos numeros");
        btnNuevosNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevosNumerosActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevosNumeros);
        btnNuevosNumeros.setBounds(440, 30, 300, 35);

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator23);
        jSeparator23.setBounds(510, 70, 20, 710);

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setText("Forma");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(630, 80, 90, 19);

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator24);
        jSeparator24.setBounds(530, 140, 220, 10);

        jSeparator25.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator25);
        jSeparator25.setBounds(810, 340, 220, 10);

        FOquintilla.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FOquintilla.setText("FO");
        getContentPane().add(FOquintilla);
        FOquintilla.setBounds(980, 340, 40, 40);

        jSeparator26.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator26);
        jSeparator26.setBounds(1380, 120, 20, 190);

        jSeparator27.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator27);
        jSeparator27.setBounds(1030, 110, 20, 270);

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setText("Pachuca");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(820, 150, 60, 19);

        jSeparator28.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator28);
        jSeparator28.setBounds(810, 140, 220, 10);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel35.setText("1 Par");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(820, 180, 50, 19);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel36.setText("Quintilla");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(820, 350, 60, 19);

        jSeparator29.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator29);
        jSeparator29.setBounds(810, 380, 220, 10);

        jSeparator30.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator30);
        jSeparator30.setBounds(810, 200, 220, 10);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel37.setText("2 Pares");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(820, 210, 70, 19);

        jSeparator31.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator31);
        jSeparator31.setBounds(810, 240, 220, 10);

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel38.setText("Tercia");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(820, 250, 50, 19);

        jSeparator32.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator32);
        jSeparator32.setBounds(810, 270, 220, 10);

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel39.setText("Full");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(820, 280, 50, 19);

        jSeparator33.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator33);
        jSeparator33.setBounds(810, 310, 220, 10);

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel40.setText("Poker");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(820, 320, 60, 19);

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel41.setText("Juego");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(830, 110, 60, 30);

        jSeparator34.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator34.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator34);
        jSeparator34.setBounds(890, 110, 20, 270);

        FEquintilla.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FEquintilla.setText("FE");
        getContentPane().add(FEquintilla);
        FEquintilla.setBounds(900, 340, 70, 40);

        jSeparator35.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator35.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator35);
        jSeparator35.setBounds(960, 110, 20, 270);

        jSeparator36.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator36);
        jSeparator36.setBounds(810, 170, 220, 10);

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel43.setText("FE");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(910, 109, 40, 30);

        FEpachuca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FEpachuca.setText("FE");
        getContentPane().add(FEpachuca);
        FEpachuca.setBounds(900, 140, 80, 30);

        FEunPar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FEunPar.setText("FE");
        getContentPane().add(FEunPar);
        FEunPar.setBounds(900, 170, 70, 30);

        FEdosPares.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FEdosPares.setText("FE");
        getContentPane().add(FEdosPares);
        FEdosPares.setBounds(900, 210, 70, 30);

        FEtercia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FEtercia.setText("FE");
        getContentPane().add(FEtercia);
        FEtercia.setBounds(900, 240, 70, 30);

        FEfull.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FEfull.setText("FE");
        getContentPane().add(FEfull);
        FEfull.setBounds(900, 270, 70, 30);

        FEpoker.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FEpoker.setText("FE");
        getContentPane().add(FEpoker);
        FEpoker.setBounds(900, 310, 70, 30);

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel50.setText("FO");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(980, 110, 40, 30);

        FOpachuca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FOpachuca.setText("FO");
        getContentPane().add(FOpachuca);
        FOpachuca.setBounds(980, 140, 40, 30);

        FOunPar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FOunPar.setText("FO");
        getContentPane().add(FOunPar);
        FOunPar.setBounds(980, 170, 40, 30);

        FOdosPares.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FOdosPares.setText("FO");
        getContentPane().add(FOdosPares);
        FOdosPares.setBounds(980, 210, 40, 30);

        FOtercia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FOtercia.setText("FO");
        getContentPane().add(FOtercia);
        FOtercia.setBounds(980, 240, 40, 30);

        FOfull.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FOfull.setText("FO");
        getContentPane().add(FOfull);
        FOfull.setBounds(980, 270, 40, 30);

        FOpoker.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FOpoker.setText("FO");
        getContentPane().add(FOpoker);
        FOpoker.setBounds(980, 310, 40, 30);

        lblX2calculadaForma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblX2calculadaForma.setText("x² calculada: ");
        getContentPane().add(lblX2calculadaForma);
        lblX2calculadaForma.setBounds(530, 360, 170, 19);

        lblX2TabForma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblX2TabForma.setText("x² Tab: ");
        getContentPane().add(lblX2TabForma);
        lblX2TabForma.setBounds(540, 380, 170, 19);

        lblResultadoPoker.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoPoker.setText("jLabel33");
        getContentPane().add(lblResultadoPoker);
        lblResultadoPoker.setBounds(850, 480, 160, 19);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setText("x² calc ≤ x²tab ");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(1520, 480, 110, 19);

        lblAceptacionForma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAceptacionForma.setText("jLabel323");
        getContentPane().add(lblAceptacionForma);
        lblAceptacionForma.setBounds(610, 650, 130, 19);

        jSeparator37.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator37.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator37);
        jSeparator37.setBounds(790, 70, 20, 710);

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel42.setText("Poker");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(910, 70, 41, 30);

        jSeparator38.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator38.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator38);
        jSeparator38.setBounds(1060, 70, 20, 730);

        lblValorHcorridas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValorHcorridas.setText("h: ");
        getContentPane().add(lblValorHcorridas);
        lblValorHcorridas.setBounds(1080, 120, 130, 19);

        lblValorEcorridas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValorEcorridas.setText("E(h):");
        getContentPane().add(lblValorEcorridas);
        lblValorEcorridas.setBounds(1080, 180, 190, 16);

        lblValorVcorridas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValorVcorridas.setText("V(h):");
        getContentPane().add(lblValorVcorridas);
        lblValorVcorridas.setBounds(1080, 240, 200, 19);

        lblZcalculadaCorridas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblZcalculadaCorridas.setText("Z Calculada: ");
        getContentPane().add(lblZcalculadaCorridas);
        lblZcalculadaCorridas.setBounds(1080, 290, 200, 19);

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel44.setText("-Ztab ≤ Z Calculada ≤ Ztab");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(1090, 390, 200, 19);

        lblZtabCorridas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblZtabCorridas.setText("Ztab: ");
        getContentPane().add(lblZtabCorridas);
        lblZtabCorridas.setBounds(1080, 330, 210, 19);

        lblAceptacionCorridas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAceptacionCorridas.setText("jLabel45");
        getContentPane().add(lblAceptacionCorridas);
        lblAceptacionCorridas.setBounds(1150, 690, 140, 16);

        lblValoresAceptacionCorridas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValoresAceptacionCorridas.setText("jLabel45");
        getContentPane().add(lblValoresAceptacionCorridas);
        lblValoresAceptacionCorridas.setBounds(1090, 440, 200, 19);

        jSeparator39.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator39.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator39);
        jSeparator39.setBounds(1300, 70, 2, 710);

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel45.setText("Corridas");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(1160, 70, 80, 30);

        jSeparator40.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator40);
        jSeparator40.setBounds(1380, 120, 440, 2);

        jSeparator41.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator41.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator41);
        jSeparator41.setBounds(1710, 120, 10, 190);

        jSeparator42.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator42);
        jSeparator42.setBounds(1380, 170, 440, 10);

        jSeparator43.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator43);
        jSeparator43.setBounds(1320, 320, 440, 0);

        jSeparator44.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator44);
        jSeparator44.setBounds(1380, 210, 440, 0);

        jSeparator45.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator45);
        jSeparator45.setBounds(1380, 210, 440, 10);

        jSeparator46.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator46.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator46);
        jSeparator46.setBounds(1820, 120, 20, 190);

        jSeparator47.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator47.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator47);
        jSeparator47.setBounds(1490, 120, 10, 190);

        jSeparator48.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator48.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator48);
        jSeparator48.setBounds(1600, 120, 10, 190);

        jSeparator49.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator49);
        jSeparator49.setBounds(1380, 310, 440, 10);

        jSeparator50.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator50);
        jSeparator50.setBounds(1380, 260, 440, 10);

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel46.setText("0.25");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(1420, 310, 30, 19);

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel47.setText("1.0");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(1760, 310, 30, 19);

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel48.setText("0.75");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(1640, 320, 30, 19);

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel49.setText("0.5");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(1540, 320, 30, 19);

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel51.setText("0.25");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(1350, 270, 30, 19);

        jLabel52.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel52.setText("0.5");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(1350, 230, 30, 19);

        jLabel53.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel53.setText("0.75");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(1350, 180, 30, 19);

        jLabel54.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel54.setText("1.0");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(1350, 140, 30, 19);

        lblCasilla1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla1.setText("0");
        getContentPane().add(lblCasilla1);
        lblCasilla1.setBounds(1400, 280, 60, 20);

        lblCasilla2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla2.setText("0");
        getContentPane().add(lblCasilla2);
        lblCasilla2.setBounds(1410, 230, 60, 19);

        lblCasilla3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla3.setText("0");
        getContentPane().add(lblCasilla3);
        lblCasilla3.setBounds(1410, 180, 60, 19);

        lblCasilla4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla4.setText("0");
        getContentPane().add(lblCasilla4);
        lblCasilla4.setBounds(1410, 140, 60, 19);

        lblCasilla5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla5.setText("0");
        getContentPane().add(lblCasilla5);
        lblCasilla5.setBounds(1520, 280, 70, 19);

        lblCasilla6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla6.setText("0");
        getContentPane().add(lblCasilla6);
        lblCasilla6.setBounds(1520, 230, 70, 19);

        lblCasilla7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla7.setText("0");
        getContentPane().add(lblCasilla7);
        lblCasilla7.setBounds(1520, 180, 70, 19);

        lblCasilla8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla8.setText("0");
        getContentPane().add(lblCasilla8);
        lblCasilla8.setBounds(1520, 140, 70, 19);

        lblCasilla9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla9.setText("0");
        getContentPane().add(lblCasilla9);
        lblCasilla9.setBounds(1630, 280, 60, 19);

        lblCasilla10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla10.setText("0");
        getContentPane().add(lblCasilla10);
        lblCasilla10.setBounds(1630, 230, 70, 19);

        lblCasilla11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla11.setText("0");
        getContentPane().add(lblCasilla11);
        lblCasilla11.setBounds(1630, 180, 70, 19);

        lblCasilla12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla12.setText("0");
        getContentPane().add(lblCasilla12);
        lblCasilla12.setBounds(1630, 140, 70, 19);

        lblCasilla13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla13.setText("0");
        getContentPane().add(lblCasilla13);
        lblCasilla13.setBounds(1740, 280, 70, 19);

        lblCasilla14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla14.setText("0");
        getContentPane().add(lblCasilla14);
        lblCasilla14.setBounds(1740, 230, 70, 19);

        lblCasilla15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla15.setText("0");
        getContentPane().add(lblCasilla15);
        lblCasilla15.setBounds(1740, 180, 70, 19);

        lblCasilla16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCasilla16.setText("0");
        getContentPane().add(lblCasilla16);
        lblCasilla16.setBounds(1740, 140, 70, 19);

        lblParejasSeries.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblParejasSeries.setText("Parejas: ");
        getContentPane().add(lblParejasSeries);
        lblParejasSeries.setBounds(1320, 360, 130, 19);

        lblFEseries.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFEseries.setText("FE:");
        getContentPane().add(lblFEseries);
        lblFEseries.setBounds(1320, 390, 170, 16);

        jLabel55.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel55.setText("x² calc ≤ x²tab ");
        getContentPane().add(jLabel55);
        jLabel55.setBounds(610, 400, 110, 19);

        lblValoresSeries.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValoresSeries.setText("jLabel56");
        getContentPane().add(lblValoresSeries);
        lblValoresSeries.setBounds(1530, 510, 210, 19);

        lblAceptacionSeries.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAceptacionSeries.setText("jLabel56");
        getContentPane().add(lblAceptacionSeries);
        lblAceptacionSeries.setBounds(1530, 710, 150, 30);

        lblX2calculadaSeries.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblX2calculadaSeries.setText("x² calculada: ");
        getContentPane().add(lblX2calculadaSeries);
        lblX2calculadaSeries.setBounds(1320, 450, 180, 16);

        lblx2TabSeries.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblx2TabSeries.setText("x² Tab: ");
        getContentPane().add(lblx2TabSeries);
        lblx2TabSeries.setBounds(1320, 420, 130, 19);

        lblAceptacionNumeros.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAceptacionNumeros.setText("jLabel56");
        getContentPane().add(lblAceptacionNumeros);
        lblAceptacionNumeros.setBounds(840, 30, 470, 24);

        btnSmulacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSmulacion.setText("Simulacion");
        btnSmulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmulacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSmulacion);
        btnSmulacion.setBounds(1420, 20, 140, 40);

        imagenAceptacionMedias.setText("jLabel56");
        getContentPane().add(imagenAceptacionMedias);
        imagenAceptacionMedias.setBounds(10, 420, 230, 210);

        imagenAceptacionVarianza.setText("jLabel56");
        getContentPane().add(imagenAceptacionVarianza);
        imagenAceptacionVarianza.setBounds(260, 440, 240, 200);

        imagenAceptacionForma.setText("jLabel56");
        getContentPane().add(imagenAceptacionForma);
        imagenAceptacionForma.setBounds(550, 450, 230, 190);

        imagenAceptacionPoker.setText("jLabel56");
        getContentPane().add(imagenAceptacionPoker);
        imagenAceptacionPoker.setBounds(800, 510, 250, 190);

        imagenAceptacionCorridas.setText("jLabel56");
        getContentPane().add(imagenAceptacionCorridas);
        imagenAceptacionCorridas.setBounds(1070, 470, 220, 210);

        imageAceptacionSeries.setText("jLabel57");
        getContentPane().add(imageAceptacionSeries);
        imageAceptacionSeries.setBounds(1390, 530, 340, 180);
        getContentPane().add(panel);
        panel.setBounds(0, 0, 1840, 70);
        getContentPane().add(panelAbajo);
        panelAbajo.setBounds(0, 70, 1840, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarActionPerformed
        Interfaz u = new Interfaz();
        contadorAceptacion = 0;
        for (int i = 0; i < u.arrayAleatorios.length; i++) {
            System.out.println(u.arrayAleatorios[i]);
            
        }
        
        
         if(rd90.isSelected()){
            zTab = 1.645;
            confiabilidad = 10;
           chiCuadradaPoker = 10.64;
           X2tabSeriesTabla =22.3;
        }else if(rd95.isSelected()){
            zTab = 1.96;
            chiCuadradaPoker=12.59;
            X2tabSeriesTabla = 25;
            
        }else if(rd99.isSelected()){
            zTab =2.575;
            chiCuadradaPoker = 16.81;
            X2tabSeriesTabla = 30.6;
        }
         
         pruebaMedias();
         pruebaVarianza();
         pruebaForma();
         pruebaPoker();
         pruebaCorridas();
         pruebaSeries();
         
         lblAceptacionForma.setVisible(true);
         lblresultadoForma.setVisible(true);
         lblValoresAceptacionCorridas.setVisible(true);
         lblAceptacionCorridas.setVisible(true);
         lblValoresSeries.setVisible(true);
       lblAceptacionSeries.setVisible(true);
       lblAceptacionNumeros.setVisible(true);
       
       JOptionPane.showMessageDialog(null, "pruebas aceptadas: " + contadorAceptacion);
       
       if(contadorAceptacion>=4){
           if(u.contadorConjunto==1){
           u.primerConjunto = new double[u.arrayAleatorios.length];
           
           for (int i = 0; i < u.arrayAleatorios.length; i++) {
               u.primerConjunto[i] = u.arrayAleatorios[i];
               
                }
          
           }else{
               u.segundoConjunto = new double[u.arrayAleatorios.length];
           
           for (int i = 0; i < u.arrayAleatorios.length; i++) {
               u.segundoConjunto[i] = u.arrayAleatorios[i];
               
                }
           
                
           }
             lblAceptacionNumeros.setText(String.valueOf(u.contadorConjunto)+"° conjunto de numeros aceptado");
             lblAceptacionNumeros.setForeground(new Color(0,152,56));
             btnRealizar.setVisible(false);
             btnNuevosNumeros.setText("Generar 2° conjunto de numeros");
             u.contadorConjunto++;
       
       }else{
           lblAceptacionNumeros.setText(String.valueOf(u.contadorConjunto)+"° conjunto de numeros no aceptado");
            lblAceptacionNumeros.setForeground(Color.red);
       }
       
       if(u.contadorConjunto==3){
           btnSmulacion.setVisible(true);
           btnRealizar.setVisible(false);
           btnNuevosNumeros.setVisible(false);
       }
         
         
    }//GEN-LAST:event_btnRealizarActionPerformed

    private void rd99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd99ActionPerformed

    private void btnNuevosNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevosNumerosActionPerformed
       Interfaz u = new Interfaz();
       u.setVisible(true);
        this.setVisible(false);
       
        
    }//GEN-LAST:event_btnNuevosNumerosActionPerformed

    private void btnSmulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmulacionActionPerformed
    
        Simulacion s = new Simulacion();
        s.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_btnSmulacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebas().setVisible(true);
            }
        });
    }
    
    
    public void pruebaMedias(){
        Interfaz u = new Interfaz();
        String ruta = "";
        
        double limiteInferior = (0.5-zTab * (Math.sqrt(1.0/(12.0*u.arrayAleatorios.length))));
        double limiteSuperior = (0.5+zTab * (Math.sqrt(1.0/(12.0*u.arrayAleatorios.length))));
         limiteInferior = Math.round(limiteInferior*100000)/ 100000d;
         limiteSuperior = Math.round(limiteSuperior*100000)/ 100000d;
         lblMedias.setText("Media:  "+String.valueOf(media));
         lblLimiteInferior.setText("Limite inferior:  "+String.valueOf(limiteInferior));
         lblLimiteSuperior.setText("Limite Superior: "   +String.valueOf(limiteSuperior));
         lblZtab.setText(String.valueOf("Ztab:  "+zTab));
         
       lblAceptacion.setText(limiteInferior + " <= " + media+ " <= " + limiteSuperior);
       lblAceptacion.setVisible(true);
       
       if(limiteInferior <= media && media <= limiteSuperior){
           lblResultado.setVisible(true);
           lblResultado.setText("Se acepta H0");
           lblResultado.setForeground(new Color(0,152,56));
           contadorAceptacion++;
           ruta = "src\\main\\java\\imagenes\\aceptadaMedias.jpg";
          
       }else{
           lblResultado.setVisible(true);
           lblResultado.setText("Se rechaza H0");
           lblResultado.setForeground(Color.red);
           ruta = "src\\main\\java\\imagenes\\rechazadaMedias.jpg";
       }
         ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(imagenAceptacionMedias.getWidth(), imagenAceptacionMedias.getHeight(), Image.SCALE_DEFAULT));
        imagenAceptacionMedias.setIcon(icono);
        this.repaint();
         imagenAceptacionMedias.setVisible(true);
        
        
    }
    
    public void pruebaVarianza(){
        Interfaz u = new Interfaz();
        String ruta = "";
        double sumatoria = 0;
        double auxiliar;
        double resultadoV = 0;
        double valorX2 = 0;
        double limiteSuperior = 0;
        double limiteInferior = 0;
        double auxiliar2 = 0;
        double columna05 [] = new double [37];
        int renglon = u.arrayAleatorios.length-1;
        arreglosTablas ar = new arreglosTablas();
 
        double media2 = 0.42552;
        for (int i = 0; i <u.arrayAleatorios.length; i++) {
            auxiliar = u.arrayAleatorios[i] - media;
            sumatoria += Math.pow(auxiliar, 2);
            auxiliar = 0;
            
        }
        sumatoria = Math.round(sumatoria*100000) / 100000d;
        
        resultadoV = sumatoria / (u.arrayAleatorios.length - 1);
        resultadoV = Math.round(resultadoV*100000) / 100000d;
        
        confiabilidad = (confiabilidad / 100) / 2;
        
        
    
        lblAceptacionVarianza.setVisible(true);
        if(rd90.isSelected()){
            if(renglon <30){
                renglon = u.arrayAleatorios.length-2;
            }else if(renglon>=30 && renglon<40){
                renglon = 29;
            }else if(renglon>=40 && renglon < 50 ){
                renglon = 30;        
            }else if(renglon>=50 && renglon <60){
                renglon = 31;
            }else if(renglon >=60 && renglon < 70){
                renglon =32; 
            }else if(renglon >=70 && renglon < 80){
                renglon=33;
            }else if(renglon >=80 && renglon<90){
                renglon = 34;
            }else if(renglon >=90 && renglon <100){
                renglon = 35;
            }else if(renglon >= 100 && renglon < 200){
                renglon = 36;
            }else if(renglon >= 200 && renglon < 300){
                renglon = 37;
            }else if(renglon >= 300 && renglon < 400){
                renglon = 38;
            }else if(renglon >= 400 && renglon < 500){
                renglon = 39;
            }else if(renglon >= 500 && renglon < 600){
                renglon = 40;
            }
            
            valorX2 = ar.columna05[renglon];
            
            
            auxiliar = u.arrayAleatorios.length - 1;
          limiteSuperior = valorX2 / (12*auxiliar);
        limiteSuperior = Math.round(limiteSuperior*100000)/ 100000d;
       
        auxiliar2 = 1-valorX2;
        limiteInferior = ar.columna95[renglon]/(12*auxiliar);
        limiteInferior = Math.round(limiteInferior*100000) / 100000d;
        
     
        
        lblVarianza.setText("Varianza: " + String.valueOf(resultadoV));
        lblVarianzaSuperior.setText("limite superior: " + String.valueOf(limiteSuperior));
        lblVarianzaInferior.setText("limite inferior: " + String.valueOf(limiteInferior));
        lblValoresVarianza.setText(String.valueOf(limiteInferior) + " ≤ " + String.valueOf(resultadoV) + " ≤ " + String.valueOf(limiteSuperior));
        lblValoresVarianza.setVisible(true);
        
        if(limiteInferior <= resultadoV && resultadoV <= limiteSuperior){
            lblAceptacionVarianza.setText("Se acepta H0");
            lblAceptacionVarianza.setForeground(new Color(0,152,56));
            contadorAceptacion++;
              ruta = "src\\main\\java\\imagenes\\aceptadaMedias.jpg";
        }else{
            lblAceptacionVarianza.setText("Se rechaza H0");
            lblAceptacionVarianza.setForeground(Color.red);
            ruta = "src\\main\\java\\imagenes\\rechazadaMedias.jpg";
        }
             
     
        }else if(rd95.isSelected()){
             if(renglon <30){
                renglon = u.arrayAleatorios.length-2;
            }else if(renglon>=30 && renglon<40){
                renglon = 29;
            }else if(renglon>=40 && renglon < 50 ){
                renglon = 30;        
            }else if(renglon>=50 && renglon <60){
                renglon = 31;
            }else if(renglon >=60 && renglon < 70){
                renglon =32; 
            }else if(renglon >=70 && renglon < 80){
                renglon=33;
            }else if(renglon >=80 && renglon<90){
                renglon = 34;
            }else if(renglon >=90 && renglon <100){
                renglon = 35;
            }else if(renglon >= 100 && renglon < 200){
                renglon = 36;
            }else if(renglon >= 200 && renglon < 300){
                renglon = 37;
            }else if(renglon >= 300 && renglon < 400){
                renglon = 38;
            }else if(renglon >= 400 && renglon < 500){
                renglon = 39;
            }else if(renglon >= 500 && renglon < 600){
                renglon = 40;
            }
            
            valorX2 = ar.columna025[renglon];
             auxiliar = u.arrayAleatorios.length - 1;
        limiteSuperior = valorX2 / (12*auxiliar);
        limiteSuperior = Math.round(limiteSuperior*100000)/ 100000d;
        
        auxiliar2 = 1-valorX2;
        limiteInferior = ar.columna975[renglon]/(12*auxiliar);
        limiteInferior = Math.round(limiteInferior*100000) / 100000d;
        
       
      
        
        System.out.println("limite superior: " + limiteSuperior);
        System.out.println("Limite inferior: " + limiteInferior);
        System.out.println(auxiliar2);
        
        lblVarianza.setText("Varianza: " + String.valueOf(resultadoV));
        lblVarianzaSuperior.setText("limite superior: " + String.valueOf(limiteSuperior));
        lblVarianzaInferior.setText("limite inferior: " + String.valueOf(limiteInferior));
        lblValoresVarianza.setText(String.valueOf(limiteInferior) + " ≤ " + String.valueOf(resultadoV) + " ≤ " + String.valueOf(limiteSuperior));
        lblValoresVarianza.setVisible(true);
        
        if(limiteInferior <= resultadoV && resultadoV <= limiteSuperior){
            lblAceptacionVarianza.setText("Se acepta H0");
            lblAceptacionVarianza.setForeground(new Color(0,152,56));
            contadorAceptacion++;
              ruta = "src\\main\\java\\imagenes\\aceptadaMedias.jpg";
        }else{
            lblAceptacionVarianza.setText("Se rechaza H0");
            lblAceptacionVarianza.setForeground(Color.red);
            ruta = "src\\main\\java\\imagenes\\rechazadaMedias.jpg";
        }
            
            
        }else if(rd99.isSelected()){
             if(renglon <30){
                renglon = u.arrayAleatorios.length-2;
            }else if(renglon>=30 && renglon<40){
                renglon = 29;
            }else if(renglon>=40 && renglon < 50 ){
                renglon = 30;        
            }else if(renglon>=50 && renglon <60){
                renglon = 31;
            }else if(renglon >=60 && renglon < 70){
                renglon =32; 
            }else if(renglon >=70 && renglon < 80){
                renglon=33;
            }else if(renglon >=80 && renglon<90){
                renglon = 34;
            }else if(renglon >=90 && renglon <100){
                renglon = 35;
            }else if(renglon >= 100 && renglon < 200){
                renglon = 36;
            }else if(renglon >= 200 && renglon < 300){
                renglon = 37;
            }else if(renglon >= 300 && renglon < 400){
                renglon = 38;
            }else if(renglon >= 400 && renglon < 500){
                renglon = 39;
            }else if(renglon >= 500 && renglon < 600){
                renglon = 40;
            }
            
             valorX2 = ar.columna005[renglon];
           
             auxiliar = u.arrayAleatorios.length - 1;
            limiteSuperior = valorX2 / (12*auxiliar);
            limiteSuperior = Math.round(limiteSuperior*100000)/ 100000d;
            
            auxiliar2 = 1-valorX2;
            limiteInferior = ar.columna995[renglon]/(12*auxiliar);
            limiteInferior = Math.round(limiteInferior*100000) / 100000d;
        

            lblVarianza.setText("Varianza: " + String.valueOf(resultadoV));
            lblVarianzaSuperior.setText("limite superior: " + String.valueOf(limiteSuperior));
            lblVarianzaInferior.setText("limite inferior: " + String.valueOf(limiteInferior));
            lblValoresVarianza.setText(String.valueOf(limiteInferior) + " ≤ " + String.valueOf(resultadoV) + " ≤ " + String.valueOf(limiteSuperior));
            lblValoresVarianza.setVisible(true);
       
        if(limiteInferior <= resultadoV && resultadoV <= limiteSuperior){
            lblAceptacionVarianza.setText("Se acepta H0");
            lblAceptacionVarianza.setForeground(new Color(0,152,56));
            contadorAceptacion++;
              ruta = "src\\main\\java\\imagenes\\aceptadaMedias.jpg";
        }else{
            lblAceptacionVarianza.setText("Se rechaza H0");
            lblAceptacionVarianza.setForeground(Color.red);
            ruta = "src\\main\\java\\imagenes\\rechazadaMedias.jpg";
        }
            
            
        }
        
        ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(imagenAceptacionVarianza.getWidth(), imagenAceptacionVarianza.getHeight(), Image.SCALE_DEFAULT));
        imagenAceptacionVarianza.setIcon(icono);
        this.repaint();
         imagenAceptacionVarianza.setVisible(true);
      
       
        
    }
        public void pruebaForma(){
            String ruta = "";
            lblAceptacionPoker.setVisible(true);
            lblresultadoForma.setVisible(true);
            Interfaz u = new Interfaz();
            double cantidad = u.arrayAleatorios.length;
            int FOclase1 = 0;
            int FOclase2 = 0;
            int FOclase3 = 0;
            int FOclase4 = 0;
            int FOclase5 = 0;
            int FOclase6 = 0;
            int FOclase7 = 0;
            int FOclase8 = 0;
            int FOclase9 = 0;
            int FOclase10 = 0;
            double resultadoX2 = 0;
            double auxiliar = 0;
            double FE = cantidad/10;
            double X2tabla = 0;
           if(rd90.isSelected()){
               X2tabla = 14.68;
           }else if(rd95.isSelected()){
               X2tabla = 16.92;
           }else if(rd99.isSelected()){
               X2tabla = 21.7;
           }
           
              
            
            for (int i = 0; i <u.arrayAleatorios.length; i++) {
                if(u.arrayAleatorios [i] >=0 && u.arrayAleatorios [i] <0.1){
                    FOclase1++;
                }else if(u.arrayAleatorios[i] >=0.1 && u.arrayAleatorios [i] <0.2){
                    FOclase2++;
                }else if(u.arrayAleatorios [i] >=0.2 && u.arrayAleatorios [i] <0.3){
                    FOclase3++;
                }else if(u.arrayAleatorios [i] >=0.3 && u.arrayAleatorios[i]  <0.4){
                    FOclase4++;
                }else if(u.arrayAleatorios[i] >=0.4 && u.arrayAleatorios[i] <0.5){
                    FOclase5++;
                }else if(u.arrayAleatorios[i] >=0.5 && u.arrayAleatorios[i] <0.6){
                    FOclase6++;
                }else if(u.arrayAleatorios[i] >=0.6 && u.arrayAleatorios[i] <0.7){
                    FOclase7++;
                }else if(u.arrayAleatorios[i] >=0.7 && u.arrayAleatorios[i] <0.8){
                    FOclase8++;
                }else if(u.arrayAleatorios[i] >=0.8 && u.arrayAleatorios[i] <0.9){
                    FOclase9++;
                }else if(u.arrayAleatorios[i] >=0.9 && u.arrayAleatorios[i] <=1.0){
                    FOclase10++;
                }
                
            }
            
            int arrayFO [] = {FOclase1,FOclase2,FOclase3,FOclase4,FOclase5, FOclase6, FOclase7, FOclase8, FOclase9, FOclase10};
                for (int j = 0; j <arrayFO.length; j++) {
                    auxiliar = FE - arrayFO[j];
                    resultadoX2 += Math.pow(auxiliar, 2) / FE;

                }
                
                resultadoX2 =Math.round(resultadoX2*100000)/ 100000d;
            
           
              lblFOclase1.setText(String.valueOf(FOclase1));
                lblFOclase2.setText(String.valueOf(FOclase2));
                lblFOclase3.setText(String.valueOf(FOclase3));
                lblFOclase4.setText(String.valueOf(FOclase4));
                lblFOclase5.setText(String.valueOf(FOclase5));
                lblFOclase6.setText(String.valueOf(FOclase6));
                lblFOclase7.setText(String.valueOf(FOclase7));
                lblFOclase8.setText(String.valueOf(FOclase8));
                lblFOclase9.setText(String.valueOf(FOclase9));
                lblFOclase10.setText(String.valueOf(FOclase10));
                lblresultadoForma.setText(String.valueOf(resultadoX2) + " <= " + X2tabla);
                
            if(resultadoX2 <= X2tabla){
                lblAceptacionForma.setText("Se acepta H0");
                lblAceptacionForma.setForeground(new Color(0,152,56));
                contadorAceptacion++;
                ruta = "src\\main\\java\\imagenes\\aceptadaForma.jpg";
            }else{
                lblAceptacionForma.setText("Se rechaza H0");
                lblAceptacionForma.setForeground(Color.red);
                 ruta = "src\\main\\java\\imagenes\\rechazadaForma.jpg";
            }
            FE1.setText(String.valueOf(FE));
            FE2.setText(String.valueOf(FE));
            FE3.setText(String.valueOf(FE));
            FE4.setText(String.valueOf(FE));
            FE5.setText(String.valueOf(FE));
            FE6.setText(String.valueOf(FE));
            FE7.setText(String.valueOf(FE));
            FE8.setText(String.valueOf(FE));
            FE9.setText(String.valueOf(FE));
            FE10.setText(String.valueOf(FE));
            
            lblX2calculadaForma.setText("x² calculada: " + resultadoX2);
            lblX2TabForma.setText("x² Tab: " + X2tabla);
            
            ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(imagenAceptacionForma.getWidth(), imagenAceptacionForma.getHeight(), Image.SCALE_DEFAULT));
        imagenAceptacionForma.setIcon(icono);
        this.repaint();
         imagenAceptacionForma.setVisible(true);
        }
        public void pruebaPoker(){
            String ruta = "";
            double ejemplo = 0;
        int auxiliar1 = 0;
        int auxiliar2 = 0;
        int auxiliar3 =0;
        int auxiliarSimilitudes = 0;
        double chiCuadradaCalculada=0;
        int p =5;
        int arreglo [] = new int[5];
        int arregloPoker [] = new int[7];
        double arregloProbabilidades [] ={0.3024,0.5040,0.1080,0.0720, 0.0090,0.0045,0.0001};
        Interfaz u = new Interfaz();

       
        
        for(int k=0; k<u.arrayAleatorios.length; k++ ){
            ejemplo = u.arrayAleatorios[k];
        
        String cadena = String.valueOf(ejemplo);
        System.out.println(ejemplo);
        
        if(cadena.length()<7){
            int aux = 7-cadena.length();
            p = p-aux;
        }
        
        
        for (int i = 0; i < p; i++) {
            arreglo[i] = Integer.parseInt(String.valueOf(cadena.charAt(i+2)));
        }

       Arrays.sort(arreglo);
       
        for (int i = 0; i <5; i++) {
            System.out.print(arreglo[i]);
        }
        System.out.println("");
        for (int i = 0; i < 4; i++) {
            
           if(arreglo[i+1]==arreglo[i]){
                
                    if (auxiliar2==0) {
                        auxiliar1++;
                   
                    }else{
                        auxiliarSimilitudes++;
                    }
                    
          
                }else{
               auxiliar2++;
           }
         if(i==1 && auxiliar2==2){
                auxiliar3=1;
            }
         }
   
        if (auxiliar1==1 && auxiliarSimilitudes==1 || auxiliarSimilitudes ==2 && auxiliar2==2 && auxiliar1==0 && auxiliar3==0) {
            System.out.println("dos pares");
            arregloPoker[2]++;
 
        }else if(auxiliar1==1 && auxiliarSimilitudes==0 || auxiliarSimilitudes==1 && auxiliar1==0){
            System.out.println("un par");
            arregloPoker[1]++;
        }else if(auxiliar1==1 && auxiliarSimilitudes==2 || auxiliarSimilitudes==1 && auxiliar1==2){
            System.out.println("full");
            arregloPoker[4]++;
        }else if(auxiliar1==2 && auxiliarSimilitudes==0 || auxiliarSimilitudes==2 && auxiliar1==0 && auxiliar3==1){
            System.out.println("tercia");
            arregloPoker[3]++;
        }else if(auxiliar1==3 || auxiliarSimilitudes==3){
            System.out.println("poker");
            arregloPoker[5]++;
        }else if(auxiliar1==4){
            System.out.println("quintilla");
            arregloPoker[6]++;
        }else if(auxiliar1==0){
            System.out.println("pachuca");
            arregloPoker[0]++;
                }
                auxiliar1=0;
                auxiliar2=0;
                auxiliar3=0;
                auxiliarSimilitudes=0;
                p=5;
                arreglo[0] = 0;
                arreglo[1] = 0;
                arreglo[2] = 0;
                arreglo[3] = 0;
                arreglo[4] = 0;
                
                
                
                System.out.println("");
                }
        
                for (int i = 0; i < 7; i++) {
                    double auxiliar = 0;
                    auxiliar = ((arregloProbabilidades[i]*20)-arregloPoker[i]);
                    auxiliar = Math.round(((Math.pow(auxiliar, 2)) / (arregloProbabilidades[i]*20)*100000))/100000d;
                    chiCuadradaCalculada += auxiliar; 
                    
                }
                   chiCuadradaCalculada = Math.round(chiCuadradaCalculada*100000)/ 100000d;
        
        
        
        
                System.out.println("");
                System.out.println("");
                System.out.println("dos pares: " + arregloPoker[2]);
                System.out.println("un par: " + arregloPoker[1]);
                System.out.println("full: " + arregloPoker[4]);
                System.out.println("tercia: " + arregloPoker[3]);
                System.out.println("poker: " + arregloPoker[5]);
                System.out.println("quintilla: " + arregloPoker[6]);
                System.out.println("pachuca: " + arregloPoker[0]);
                
                System.out.println("X calculada = " + chiCuadradaCalculada);
                
                FOdosPares.setText(String.valueOf(arregloPoker[2]));
                FOunPar.setText(String.valueOf(arregloPoker[1]));
                FOfull.setText(String.valueOf(arregloPoker[4]));
                FOtercia.setText(String.valueOf(arregloPoker[3]));
                FOpoker.setText(String.valueOf(arregloPoker[5]));
                FOquintilla.setText(String.valueOf(arregloPoker[6]));
                FOpachuca.setText(String.valueOf(arregloPoker[0]));
                lblX2calculadaPoker.setText("x² calculada: " + String.valueOf(chiCuadradaCalculada));
                lblX2TabPoker.setText("x² Tab:"+ String.valueOf(chiCuadradaPoker));
                lblResultadoPoker.setText(String.valueOf(chiCuadradaCalculada) + " ≤ " + String.valueOf(chiCuadradaPoker));
                lblResultadoPoker.setVisible(true);
                
                FEdosPares.setText(String.valueOf(Math.round((0.1080*u.arrayAleatorios.length)*100000)/ 100000d));
                FEpachuca.setText(String.valueOf(Math.round((0.3024*u.arrayAleatorios.length)*100000)/ 100000d));
                FEunPar.setText(String.valueOf(Math.round((0.5040*u.arrayAleatorios.length)*100000)/ 100000d));
                FEtercia.setText(String.valueOf(Math.round((0.0720*u.arrayAleatorios.length)*100000)/ 100000d));
                FEfull.setText(String.valueOf(Math.round((0.0090*u.arrayAleatorios.length)*100000)/ 100000d));
                FEpoker.setText(String.valueOf(Math.round((0.0045*u.arrayAleatorios.length)*100000)/ 100000d));
                FEquintilla.setText(String.valueOf(Math.round((0.0001*u.arrayAleatorios.length)*100000)/ 100000d));
                
            
                if (chiCuadradaCalculada<= chiCuadradaPoker) {
                lblAceptacionPoker.setText("Se acepta");
                lblAceptacionPoker.setForeground(new Color(0,152,56));
                contadorAceptacion++;
                 ruta = "src\\main\\java\\imagenes\\aceptadaForma.jpg";
                
            }else{
                    lblAceptacionPoker.setText("No se acepta");
                    lblAceptacionPoker.setForeground(Color.red);
                    ruta = "src\\main\\java\\imagenes\\rechazadaForma.jpg";
                }
                
                ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(imagenAceptacionPoker.getWidth(), imagenAceptacionPoker.getHeight(), Image.SCALE_DEFAULT));
        imagenAceptacionPoker.setIcon(icono);
        this.repaint();
         imagenAceptacionPoker.setVisible(true);
            
            
            
        }

        public void pruebaCorridas(){
            String ruta = ""; 
             double salto=3;
             double h =0;
             double E = 0;
             double V = 0;
             double Zcalculada = 0;
             double zTabNegativa = 0;
             Interfaz u = new Interfaz();
        
        for (int i = 0; i < u.arrayAleatorios.length-1; i++) {
            if(u.arrayAleatorios[i+1] > u.arrayAleatorios[i]){
               if(salto !=1){
                   h++;
               }
                
                salto=1;
            
            }else{
                if(salto!=0){
                    h++;
                }
               salto = 0;
            }
        
            }
            E = ((2.0*u.arrayAleatorios.length)-1.0) /3.0;
            E = Math.round(E*100000)/ 100000d;
            
            V = ((16.0*u.arrayAleatorios.length) - 29.0)/90.0;
            V = Math.round(V*100000)/ 100000d;
            Zcalculada = (h-E)/Math.sqrt(V);
            Zcalculada = Math.round(Zcalculada*100000)/ 100000d;
            Zcalculada = Math.abs(Zcalculada);
            
   
            zTabNegativa = zTab*-1;
            
            lblValoresAceptacionCorridas.setText(String.valueOf(zTabNegativa) + " ≤ " + String.valueOf(Zcalculada) + " ≤ "+ String.valueOf(zTab));
            
            if(zTabNegativa<= Zcalculada && Zcalculada<= zTab){
                lblAceptacionCorridas.setText("Se acepta");
                lblAceptacionCorridas.setForeground(new Color(0,152,56));
                contadorAceptacion++;
                ruta = "src\\main\\java\\imagenes\\aceptadaForma.jpg";
            }else{
                lblAceptacionCorridas.setText("No se acepta");
                lblAceptacionCorridas.setForeground(Color.red);
                  ruta = "src\\main\\java\\imagenes\\rechazadaForma.jpg";
            }
            lblValorEcorridas.setText("E(h): " + E);
            lblValorHcorridas.setText("h: " + h);
            lblValorVcorridas.setText("V(h): " + V);
            lblZtabCorridas.setText(String.valueOf("Ztab: "+zTab));
            lblZcalculadaCorridas.setText("Z calculada: " + Zcalculada);
            
            
            ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(imagenAceptacionCorridas.getWidth(), imagenAceptacionCorridas.getHeight(), Image.SCALE_DEFAULT));
        imagenAceptacionCorridas.setIcon(icono);
        this.repaint();
         imagenAceptacionCorridas.setVisible(true);
            
        }
        
        
        public void pruebaSeries(){
            Interfaz u = new Interfaz();
             double casilla [] = new double[16]; 
             double FEseries = 0;
             double X2calculadaSeries = 0;
             double auxSeries = 0;
             String ruta= "";
       
            for(int i =0; i<u.arrayAleatorios.length-1; i++){
            if(u.arrayAleatorios[i] <= 0.25 && u.arrayAleatorios[i+1]<=0.25){
                casilla[0]++;
                System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 1);
                
                }else if(u.arrayAleatorios[i] <= 0.25 && u.arrayAleatorios[i+1]>0.25 && u.arrayAleatorios[i+1]<=0.5){
                    casilla[1]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 2);
            
                }else if(u.arrayAleatorios[i] <= 0.25 && u.arrayAleatorios[i+1]>0.5 && u.arrayAleatorios[i+1]<=0.75){
                    casilla[2]++;
                   System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 3);
                    
                }else if(u.arrayAleatorios[i] <= 0.25 && u.arrayAleatorios[i+1]>0.75 && u.arrayAleatorios[i+1]<=1.0){
                    casilla[3]++;
                  System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 4);
                    
                }else if(u.arrayAleatorios[i] >0.25 && u.arrayAleatorios[i] <=0.5 && u.arrayAleatorios[i+1]<=0.25){
                    casilla[4]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 5);
                    
                }else if(u.arrayAleatorios[i] >0.25 && u.arrayAleatorios[i] <=0.5 && u.arrayAleatorios[i+1]>0.25 && u.arrayAleatorios[i+1]<=0.5){
                    casilla[5]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 6);
                    
                }else if(u.arrayAleatorios[i] >0.25 && u.arrayAleatorios[i] <=0.5 && u.arrayAleatorios[i+1]>0.5 && u.arrayAleatorios[i+1]<=0.75){
                    casilla[6]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 7);
                    
                }else if(u.arrayAleatorios[i] >0.25 && u.arrayAleatorios[i] <=0.5 && u.arrayAleatorios[i+1]>0.75 && u.arrayAleatorios[i+1]<=1.0){
                     casilla[7]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 8);
                     
                }else if(u.arrayAleatorios[i] >0.5 && u.arrayAleatorios[i] <=0.75 && u.arrayAleatorios[i+1]<=0.25){
                    casilla[8]++;
                System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 9);
                    
                }else if(u.arrayAleatorios[i] >0.5 && u.arrayAleatorios[i] <=0.75 && u.arrayAleatorios[i+1]>0.25 && u.arrayAleatorios[i+1]<=0.5){
                    casilla[9]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 10);
                    
                }else if(u.arrayAleatorios[i] >0.5 && u.arrayAleatorios[i] <=0.75 && u.arrayAleatorios[i+1]>0.5 && u.arrayAleatorios[i+1]<=0.75){
                    casilla[10]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 11);
                    
                }else if(u.arrayAleatorios[i] >0.5 && u.arrayAleatorios[i] <=0.75 && u.arrayAleatorios[i+1]>0.75 && u.arrayAleatorios[i+1]<=1.0){
                    casilla[11]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 12);
                    
                }else if(u.arrayAleatorios[i] >0.75 && u.arrayAleatorios[i] <=1.0 && u.arrayAleatorios[i+1]<=0.25 ){
                    casilla[12]++;
                System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 13);
                    
                }else if(u.arrayAleatorios[i] >0.75 && u.arrayAleatorios[i] <=1.0 && u.arrayAleatorios[i+1]>0.25 && u.arrayAleatorios[i+1]<=0.5){
                    casilla[13]++;
                System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 14);
                    
                }else if(u.arrayAleatorios[i] >0.75 && u.arrayAleatorios[i] <=1.0 && u.arrayAleatorios[i+1]>0.5 && u.arrayAleatorios[i+1]<=0.75){
                    casilla[14]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 15);
                    
                }else if(u.arrayAleatorios[i] >0.75 && u.arrayAleatorios[i] <=1.0 && u.arrayAleatorios[i+1]>0.75 && u.arrayAleatorios[i+1]<=1.0){
                    casilla[15]++;
                    System.out.println(u.arrayAleatorios[i] + ", " + u.arrayAleatorios[i+1] + " " + 6);
                    
                }
            
        }
            FEseries = ((u.arrayAleatorios.length-1)/16.0);
               
               for (int i = 0; i < 16; i++) {
                auxSeries = FEseries - casilla[i];
                auxSeries = Math.pow(auxSeries, 2);
                X2calculadaSeries += auxSeries/FEseries;
                
                   
            }
            
           
            
            X2calculadaSeries = Math.round(X2calculadaSeries*100000)/ 100000d;
             
            if(X2calculadaSeries<=X2tabSeriesTabla){
                lblAceptacionSeries.setText("Se acepta");
                lblAceptacionSeries.setForeground(new Color(0,152,56));
                contadorAceptacion++;
                     ruta = "src\\main\\java\\imagenes\\aceptadaForma.jpg";
            }else{
                lblAceptacionSeries.setText("No se acepta");
                lblAceptacionSeries.setForeground(Color.red);
                 ruta = "src\\main\\java\\imagenes\\rechazadaForma.jpg";
            }
            
            ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(imageAceptacionSeries.getWidth(), imageAceptacionSeries.getHeight(), Image.SCALE_DEFAULT));
        imageAceptacionSeries.setIcon(icono);
        this.repaint();
         imageAceptacionSeries.setVisible(true);
            
         
        
        
         lblCasilla1.setText(String.valueOf(casilla[0]));
            lblCasilla2.setText(String.valueOf(casilla[1]));
            lblCasilla3.setText(String.valueOf(casilla[2]));
            lblCasilla4.setText(String.valueOf(casilla[3]));
            lblCasilla5.setText(String.valueOf(casilla[4]));
            lblCasilla6.setText(String.valueOf(casilla[5]));
            lblCasilla7.setText(String.valueOf(casilla[6]));
            lblCasilla8.setText(String.valueOf(casilla[7]));
            lblCasilla9.setText(String.valueOf(casilla[8]));
            lblCasilla10.setText(String.valueOf(casilla[9]));
            lblCasilla11.setText(String.valueOf(casilla[10]));
            lblCasilla12.setText(String.valueOf(casilla[11]));
            lblCasilla13.setText(String.valueOf(casilla[12]));
            lblCasilla14.setText(String.valueOf(casilla[13]));
            lblCasilla15.setText(String.valueOf(casilla[14]));
            lblCasilla16.setText(String.valueOf(casilla[15]));   
            
            lblFEseries.setText("FE: "+String.valueOf(FEseries));
            lblParejasSeries.setText("Parejas: "+String.valueOf((u.arrayAleatorios.length-1)));
            lblX2calculadaSeries.setText("x² calculada: "+String.valueOf(X2calculadaSeries));
            lblx2TabSeries.setText("X²tab: "+String.valueOf(X2tabSeriesTabla));
            lblValoresSeries.setText(String.valueOf(X2calculadaSeries) + " ≤ " + String.valueOf(X2tabSeriesTabla));
        
        
        
        
        }
        
        
        
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FE1;
    private javax.swing.JLabel FE10;
    private javax.swing.JLabel FE2;
    private javax.swing.JLabel FE3;
    private javax.swing.JLabel FE4;
    private javax.swing.JLabel FE5;
    private javax.swing.JLabel FE6;
    private javax.swing.JLabel FE7;
    private javax.swing.JLabel FE8;
    private javax.swing.JLabel FE9;
    private javax.swing.JLabel FEdosPares;
    private javax.swing.JLabel FEfull;
    private javax.swing.JLabel FEpachuca;
    private javax.swing.JLabel FEpoker;
    private javax.swing.JLabel FEquintilla;
    private javax.swing.JLabel FEtercia;
    private javax.swing.JLabel FEunPar;
    private javax.swing.JLabel FOdosPares;
    private javax.swing.JLabel FOfull;
    private javax.swing.JLabel FOpachuca;
    private javax.swing.JLabel FOpoker;
    private javax.swing.JLabel FOquintilla;
    private javax.swing.JLabel FOtercia;
    private javax.swing.JLabel FOunPar;
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton btnNuevosNumeros;
    private javax.swing.JButton btnRealizar;
    private javax.swing.JButton btnSmulacion;
    private javax.swing.JLabel imageAceptacionSeries;
    private javax.swing.JLabel imagenAceptacionCorridas;
    private javax.swing.JLabel imagenAceptacionForma;
    private javax.swing.JLabel imagenAceptacionMedias;
    private javax.swing.JLabel imagenAceptacionPoker;
    private javax.swing.JLabel imagenAceptacionVarianza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAceptacion;
    private javax.swing.JLabel lblAceptacionCorridas;
    private javax.swing.JLabel lblAceptacionForma;
    private javax.swing.JLabel lblAceptacionNumeros;
    private javax.swing.JLabel lblAceptacionPoker;
    private javax.swing.JLabel lblAceptacionSeries;
    private javax.swing.JLabel lblAceptacionVarianza;
    private javax.swing.JLabel lblCasilla1;
    private javax.swing.JLabel lblCasilla10;
    private javax.swing.JLabel lblCasilla11;
    private javax.swing.JLabel lblCasilla12;
    private javax.swing.JLabel lblCasilla13;
    private javax.swing.JLabel lblCasilla14;
    private javax.swing.JLabel lblCasilla15;
    private javax.swing.JLabel lblCasilla16;
    private javax.swing.JLabel lblCasilla2;
    private javax.swing.JLabel lblCasilla3;
    private javax.swing.JLabel lblCasilla4;
    private javax.swing.JLabel lblCasilla5;
    private javax.swing.JLabel lblCasilla6;
    private javax.swing.JLabel lblCasilla7;
    private javax.swing.JLabel lblCasilla8;
    private javax.swing.JLabel lblCasilla9;
    private javax.swing.JLabel lblFEseries;
    private javax.swing.JLabel lblFOclase1;
    private javax.swing.JLabel lblFOclase10;
    private javax.swing.JLabel lblFOclase2;
    private javax.swing.JLabel lblFOclase3;
    private javax.swing.JLabel lblFOclase4;
    private javax.swing.JLabel lblFOclase5;
    private javax.swing.JLabel lblFOclase6;
    private javax.swing.JLabel lblFOclase7;
    private javax.swing.JLabel lblFOclase8;
    private javax.swing.JLabel lblFOclase9;
    private javax.swing.JLabel lblLimiteInferior;
    private javax.swing.JLabel lblLimiteSuperior;
    private javax.swing.JLabel lblMedias;
    private javax.swing.JLabel lblParejasSeries;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblResultadoPoker;
    private javax.swing.JLabel lblValorEcorridas;
    private javax.swing.JLabel lblValorHcorridas;
    private javax.swing.JLabel lblValorVcorridas;
    private javax.swing.JLabel lblValoresAceptacionCorridas;
    private javax.swing.JLabel lblValoresSeries;
    private javax.swing.JLabel lblValoresVarianza;
    private javax.swing.JLabel lblVarianza;
    private javax.swing.JLabel lblVarianzaInferior;
    private javax.swing.JLabel lblVarianzaSuperior;
    private javax.swing.JLabel lblX2TabForma;
    private javax.swing.JLabel lblX2TabPoker;
    private javax.swing.JLabel lblX2calculadaForma;
    private javax.swing.JLabel lblX2calculadaPoker;
    private javax.swing.JLabel lblX2calculadaSeries;
    private javax.swing.JLabel lblZcalculadaCorridas;
    private javax.swing.JLabel lblZtab;
    private javax.swing.JLabel lblZtabCorridas;
    private javax.swing.JLabel lblresultadoForma;
    private javax.swing.JLabel lblx2TabSeries;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelAbajo;
    private javax.swing.JRadioButton rd90;
    private javax.swing.JRadioButton rd95;
    private javax.swing.JRadioButton rd99;
    // End of variables declaration//GEN-END:variables
}
